name: spot_me
description: A new Flutter A mobile application that assist Malaysian people during flood disaster.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  cloud_firestore: ^3.4.4
  cupertino_icons: ^1.0.2
  firebase_app_check: ^0.0.6+20
  firebase_auth: ^3.6.4
  firebase_core: ^1.23.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_map: ^2.2.0
  flutter_map_dragmarker: ^3.1.0
  flutter_map_location_marker: ^4.1.4
  flutter_map_marker_cluster: ^0.5.4
  flutter_native_splash: ^2.2.8
  flutter_signin_button: ^2.0.0
  flutter_svg: ^1.1.6
  geocoding: ^2.0.5
  geolocator: ^9.0.1
  google_sign_in: ^5.4.1
  latlong2: ^0.8.1
  location: ^4.4.0
  map_launcher: ^2.4.0
  mapbox_gl: ^0.16.0
  persistent_bottom_nav_bar: any
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  sign_button: ^2.0.2
  simple_ripple_animation: ^0.0.3
  twitter_api_v2: ^4.0.2
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "asset/images/logo_icon.png"
  flutter_lints: ^2.0.0

flutter_native_splash: 
  color: "#000000"
  image: asset/images/logo.png

flutter:
  uses-material-design: true
  assets:
    - asset/images/
    - asset/config/
